#!/usr/bin/env bash
#"S3 Transfer Results Begin"
#"Bucket Name","S3 Key","Size"
#"rs34.incoming.bdrc.org","112M_scans/Inbox/Mangaram/LTWA-Books/Mangaram-2017/2_Rest_of_all_collections/D28687_W1KG22207_post.tar","10240","Unable to auto-extract archive contents. Archive file was uploaded to your S3 bucket"
#"rs34.incoming.bdrc.org","incoming.6.1.tar","100079667200"
#"rs34.incoming.bdrc.org","74M_scans/Inbox/Mangaram/LTWA-Books/Mangaram-2017/2_Rest_of_all_collections/D34603.tar","10240","Unable to auto-extract archive contents. Archive file was uploaded to your S3 bucket"
#"rs34.incoming.bdrc.org","1M_scans/Inbox/Mangaram/LTWA-Books/LTWA-Books-2014-15/Groups/shAkya'i_'od_snang:W1KG17440.tar","10240","Unable to auto-extract archive contents. Archive file was uploaded to your S3 bucket"
#"rs34.incoming.bdrc.org","195M_scans/Inbox/Mangaram/LTWA-Books/Mangaram-2017/2_Rest_of_all_collections/D28855_W23749_post.tar","10240","Unable to auto-extract archive contents. Archive file was uploaded to your S3 bucket"
#"rs34.incoming.bdrc.org","incoming.chunk.77.size.tar","10240","Unable to auto-extract archive contents. Archive file was uploaded to your S3 bucket"
#"rs34.incoming.bdrc.org","scans/Inbox/Mangaram/LTWA-Books/LTWA-Books-2014-15/Groups/shAkya'i_'od_snang:W1KG17440.tar","10240","Unable to auto-extract archive contents. Archive file was uploaded to your S3 bucket"
#"rs34.processing.bdrc.org","procRest.tar","88173557760"
#"rs34.assets.bdrc.org","Assets380.16.17.42.tar.gz","11660574720"
#"S3 Transfer Results End"


# this passes
# aws s3 ls $inc/scans/Inbox/Mangaram/LTWA-Books/Mangaram-2017/2_Rest_of_all_collections/ | grep D28687_W1KG22207 # _post.tar
# aws s3 ls $inc/scans/Inbox/Mangaram/LTWA-Books/Mangaram-2017/2_Rest_of_all_collections/ | grep D28855_W23749 # _post.tar
# aws s3 ls $inc/scans/Inbox/Mangaram/LTWA-Books/Mangaram-2017/2_Rest_of_all_collections/ | grep D34603  #.tar
# incoming.6.1.tar
aws s3 ls $inc/scans/Inbox/Mangaram/LTWA-Books/LTWA-Books-2014-15/Groups/\'shAkya\'i_od_snang.*W1KG17440.tar
# aws s3 rm --recursive s3://rs34.incoming.bdrc.org/scans/Inbox/Mangaram/LTWA-Books/LTWA-Books-2014-15/Groups/scans/
#  s3 ls s3://rs34.incoming.bdrc.org/scans/Inbox/Mangaram/LTWA-Books/LTWA-Books-2014-15/Groups/  > groups
